apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlaneTemplate
metadata:
  name: vultr-control-plane
spec:
  template:
    spec:
      kubeadmConfigSpec:
        initConfiguration:
          # wait for the Vultr load balancer to start forwarding (kubeadm default is 60s)
          timeouts:
            kubernetesAPICallSeconds: 300
          nodeRegistration:
            criSocket: unix:///var/run/containerd/containerd.sock
            kubeletExtraArgs:
            - name: cgroup-driver
              value: systemd
            - name: eviction-hard
              value: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
            - name: cloud-provider
              value: external
        joinConfiguration:
          # wait for the Vultr load balancer to start forwarding (kubeadm default is 60s)
          timeouts:
            kubernetesAPICallSeconds: 300
          nodeRegistration:
            criSocket: unix:///var/run/containerd/containerd.sock
            kubeletExtraArgs:
            - name: cgroup-driver
              value: systemd
            - name: eviction-hard
              value: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
            - name: cloud-provider
              value: external