# permissions for end users to edit vultrclustertemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vultrclustertemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-vultr
    app.kubernetes.io/part-of: cluster-api-provider-vultr
    app.kubernetes.io/managed-by: kustomize
  name: vultrclustertemplate-editor-role
rules:
- apiGroups:
  - infra.cluster.x-k8s.io
  resources:
  - vultrclustertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.cluster.x-k8s.io
  resources:
  - vultrclustertemplates/status
  verbs:
  - get
