name: Checks
on:
  pull_request:
    branches:
      - main
jobs:
  Golangci-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: "latest"
          args: "./..."
  Go-Fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Run fmt
        run: |
          gofmt_files=$(gofmt -l cmd)
          if [[ -n ${gofmt_files} ]]; then
              echo 'gofmt needs running on the following files:'
              echo "${gofmt_files}"
              exit 1
          fi
          exit 0